// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl4aXIIi4i1pe74rsOHqRALu9CBIvvML4',
    appId: '1:725441572999:android:968bedce62855bff1dc822',
    messagingSenderId: '725441572999',
    projectId: 'b2b-ecommerce-db',
    storageBucket: 'b2b-ecommerce-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLW27hrGmWOdHm62dSNIgKv80jZNcrshY',
    appId: '1:725441572999:ios:c9724840904120e11dc822',
    messagingSenderId: '725441572999',
    projectId: 'b2b-ecommerce-db',
    storageBucket: 'b2b-ecommerce-db.firebasestorage.app',
    iosBundleId: 'com.example.b2bEcommerce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLt0EkNNK9LetdeKPtYJWrzZe7AM7EdhM',
    appId: '1:725441572999:web:cb042627982632181dc822',
    messagingSenderId: '725441572999',
    projectId: 'b2b-ecommerce-db',
    authDomain: 'b2b-ecommerce-db.firebaseapp.com',
    storageBucket: 'b2b-ecommerce-db.firebasestorage.app',
    measurementId: 'G-9Z4436TN3K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLW27hrGmWOdHm62dSNIgKv80jZNcrshY',
    appId: '1:725441572999:ios:c9724840904120e11dc822',
    messagingSenderId: '725441572999',
    projectId: 'b2b-ecommerce-db',
    storageBucket: 'b2b-ecommerce-db.firebasestorage.app',
    iosBundleId: 'com.example.b2bEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLt0EkNNK9LetdeKPtYJWrzZe7AM7EdhM',
    appId: '1:725441572999:web:75b7679ad657c30c1dc822',
    messagingSenderId: '725441572999',
    projectId: 'b2b-ecommerce-db',
    authDomain: 'b2b-ecommerce-db.firebaseapp.com',
    storageBucket: 'b2b-ecommerce-db.firebasestorage.app',
    measurementId: 'G-SVPCPLMRH9',
  );

}